In [ ]:
import torch
a = torch.rand(3,3)
a

tensor([[0.4092, 0.7846, 0.5991],
        [0.4461, 0.8255, 0.4045],
        [0.6998, 0.4451, 0.5189]])

In [ ]:
b = torch.rand(3)
c = torch.rand(3)
d = b * c
print(b)
print(c)
print(d)

tensor([0.7404, 0.2626, 0.6543])
tensor([0.8589, 0.1708, 0.0846])
tensor([0.6359, 0.0449, 0.0554])


In [ ]:
e = torch.rand(2,3)
f = torch.rand(3,4)
print(e @ f)

tensor([[0.4860, 0.4599, 0.0610, 0.6635],
        [1.0460, 0.7770, 0.0616, 1.2992]])


In [ ]:
torch.sin(f)

tensor([[0.3943, 0.5077, 0.0630, 0.8237],
        [0.8265, 0.4318, 0.0011, 0.6724],
        [0.7900, 0.7286, 0.1875, 0.4106]])

In [ ]:
e[0]

tensor([0.5083, 0.1451, 0.1524])

In [ ]:
e[:,1]

tensor([0.1451, 0.6915])

In [5]:
from torch import nn

class MyNetwork(nn.Module):
  def __init__(self):
    super().__init__()
    self.layer_1 = nn.Linear(4,5)
    self.layer_2 = nn.Linear(5, 10)
    self.layer_3 = nn.Linear(10, 3)


  def forward(self, x):
    y1 = self.layer_1(x)
    y2 = self.layer_2(y1)
    y3 = self.layer_3(y2)

    return y3

In [9]:
import torch
from torch.optim import SGD
from torch.nn import MSELoss

X = torch.rand(100, 4)
Y = torch.rand(100, 3)

network = MyNetwork()
opt = SGD(network.parameters(), lr=0.001)
loss_func = MSELoss()

for i in range(1000):
  y = network(X)
  loss_value = loss_func(y, Y)

  print(f"The Value of loss function is {loss_value.item()}")

  loss_value.backward()
  opt.step()

The Value of loss function is 0.7300636768341064
The Value of loss function is 0.7272493839263916
The Value of loss function is 0.7216488718986511
The Value of loss function is 0.71331787109375
The Value of loss function is 0.7023385763168335
The Value of loss function is 0.6888185143470764
The Value of loss function is 0.672888994216919
The Value of loss function is 0.6547026038169861
The Value of loss function is 0.6344311237335205
The Value of loss function is 0.612263560295105
The Value of loss function is 0.5884029865264893
The Value of loss function is 0.5630643963813782
The Value of loss function is 0.5364727973937988
The Value of loss function is 0.5088598728179932
The Value of loss function is 0.48046326637268066
The Value of loss function is 0.4515238404273987
The Value of loss function is 0.42228469252586365
The Value of loss function is 0.39298954606056213
The Value of loss function is 0.36388179659843445
The Value of loss function is 0.33520373702049255
The Value of loss f