In [2]:
import torch
a = torch.rand(3,3)
a

tensor([[0.4092, 0.7846, 0.5991],
        [0.4461, 0.8255, 0.4045],
        [0.6998, 0.4451, 0.5189]])

In [3]:
b = torch.rand(3)
c = torch.rand(3)
d = b * c
print(b)
print(c)
print(d)

tensor([0.7404, 0.2626, 0.6543])
tensor([0.8589, 0.1708, 0.0846])
tensor([0.6359, 0.0449, 0.0554])


In [6]:
e = torch.rand(2,3)
f = torch.rand(3,4)
print(e @ f)

tensor([[0.4860, 0.4599, 0.0610, 0.6635],
        [1.0460, 0.7770, 0.0616, 1.2992]])


In [7]:
torch.sin(f)

tensor([[0.3943, 0.5077, 0.0630, 0.8237],
        [0.8265, 0.4318, 0.0011, 0.6724],
        [0.7900, 0.7286, 0.1875, 0.4106]])

In [8]:
e[0]

tensor([0.5083, 0.1451, 0.1524])

In [9]:
e[:,1]

tensor([0.1451, 0.6915])

In [10]:
from torch import nn

class MyNetwork(nn.Module):
  def __init__(self):
    super().__init__()
    self.layer_1 = nn.Linear(4,5)
    self.layer_2 = nn.linear(5, 10)
    self.layer_3 = nn.linear(10, 3)


  def forward(self, x):
    y1 = self.layer_1(x)
    y2 = self.layer_2(y1)
    y3 = self.layer_3(y2)

    return y3